version: '3.7'
services:
    kong-database:
        image: postgres:12.1
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        ports:
            - "5432:5432"

    kong:
        image: kong:latest
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_USER: kong
            KONG_PG_PASSWORD: kong
            KONG_CASSANDRA_CONTACT_POINTS: kong-database
            KONG_PROXY_ACCESS_LOG: "/dev/stdout"
            KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
            KONG_PROXY_ERROR_LOG: "/dev/stderr"
            KONG_ADMIN_ERROR_LOG: "/dev/stderr"
            KONG_ADMIN_LISTEN: '0.0.0.0:8001'
            KONG_ADMIN_GUI_URL: 'http://localhost:8002'
        ports:
            - "8000:8000" # Proxy
            - "8443:8443" # Proxy SSL
            - "8001:8001" # Admin API
            - "8444:8444" # Admin API SSL
        depends_on:
            - kong-database